#Parameters specific to the MSD speleothem
archive: 'speleothem'
age_top_prior: 35500. #age at the top of the sequence
age_top_sigma: 1000. #Error on top age
depth_grid: #depth grid for the age calculation
    type: 'regular'
    start: 6.
    end: 246
    resolution: 0.2
age_truncation:
    inf: 31000.
    sup: 52000.
deporate_prior_rep: 'linear'
calc_deporate: True
deporate0: 1.5e-2
deporate_prior_sigma: 2.
lambda_deporate: 100
depth_unit: 'mm'
age_label: ''
