#Parameters specific to the GRIP ice core
age_top_prior: -39. #age at the top of the sequence
age_top_sigma: 1. #Error on top age
depth_grid: #depth grid for the age calculation
    type: 'regular'
    start: &depth_start 1.51
    end: &depth_end 3037.000
    resolution: 1.
age_truncation:
    inf: ~
    sup: 300000.