#Parameters specific to the GRIP ice core
age_top_prior: -30. #age at the top of the sequence
age_top_sigma: 0. #Error on top age
depth_grid: #depth grid for the age calculation
    type: 'regular'
    start: &depth_start 5.425
    end: &depth_end 3028.8
    resolution: 1.
age_truncation:
    inf: ~
    sup: 300000.