#TODO: From the EDC-DF synchronisation paper, it is better to remove the excess correction for the calculation of the SMB ratio.

list_drillings: ['EDC','EDML','TALDICE','DF','NGRIP','SP']

opt_method: 'trf'  #trf or lm
tr_solver: 'lsmr'

color_init: 'c'
color_obs: 'r'
color_opt: 'k'
color_mod: 'b'
color_ci: '0.8'
color_sigma: 'm'
show_initial: False
show_airlayerthick: False
